apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
    version: v2.0.0-broken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: v2.0.0-broken
    spec:
      containers:
      - name: api
        image: secretpower/payment-rba:v1
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'Simulating fatal application crash...' && exit 1"]
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database_url
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: shared-code-volume
          mountPath: /app/backend/shared
      volumes:
      - name: shared-code-volume
        configMap:
          name: shared-code
